### ISSUE TITLE
Can't call the function via /

### ISSUE THREAD

**Issue by thob** [typora-community-plugin/typora-plugin-note-snippets#2]
I'm on Linux, and I think I set it up correctly, the snippets.md is loaded successfully but `/` doesn't load anything

that's my file

![2024-08-23_13-40](https://github.com/user-attachments/assets/8774ac88-df42-4919-ba1e-03c6dafca7c0)

**Comment by plylrnsdy** [comment]
Are you using global settings?

**Comment by thob** [comment]
yes, I do

**Comment by plylrnsdy** [comment]
fixed in newest release

**Comment by thob** [comment]
doesn't work for me. `/` doesn't load anything
also,
- whatever path I enter the success message pops up (though there's no file)
- the folder icon doesn't work either, a click doesn't open anything

**Comment by plylrnsdy** [comment]
fixed "can not open the non-existent snippet folder" in 1.1.4

**Comment by thob** [comment]
seems I figured out what causeed my issue in the first place. Either I did not look good enough or the documentation is lacking precision. If I put the snippets file into `.config/Typora/plugins/settings/~/Documents/Notizen_Dokumente/.typora/snippets` it works
However this is a strange location for such a file, I think

**Comment by plylrnsdy** [comment]
the snippets folder's path is a relative path to global settings folder (or vault folder)

you just need to set it as `snippets` in global settings (it will use `.config/Typora/plugins/settings/snippets`)

**Comment by thob** [comment]
tried it, `.config/Typora/plugins/settings/snippets` doesn't work for me. It only works if I put it into the odd location I mentioned above

**Comment by plylrnsdy** [comment]
I mean you can set "Note snippets folder" with `snippets` in global settings (click "Open folder" button will open `.config/Typora/plugins/settings/snippets`)

**Comment by thob** [comment]
~~1. Open the folder button doesn't save the selected location (i.e. .config/Typora/plugins/settings/snippets)
2. If I add the location manually into the field left to the button, it still doesn't work~~

I think I got it now – sorry it was totally unclear to me

**Comment by plylrnsdy** [comment]
I see, also.

After changed the field or changed files in the snippet folder, the reload button need to be clicked for reloading snippets from the (new) folder.

Or we can relaunch Typora.
