### ISSUE TITLE
date / time stamp as snippet content

### ISSUE THREAD

**Issue by thob** [typora-community-plugin/typora-plugin-note-snippets#3]
is there some javascript one could use for a snippet pair like

date
   2024-08-25

or

time
   21:09:55

**Comment by plylrnsdy** [comment]
We can import modules. Here is an example of importing [dayjs](https://github.com/iamkun/dayjs):

Solution 1: import from network

```js
// function.js
import 'https://cdn.jsdelivr.net/npm/dayjs@1/dayjs.min.js'

export function datetime() {
  return dayjs().format('YYYY-MM-DD HH:mm:ss')
}

export function date() {
  return dayjs().format('YYYY-MM-DD')
}

export function time() {
  return dayjs().format('HH:mm:ss')
}
```

Solution 2: import from local

1. Download https://cdn.jsdelivr.net/npm/dayjs@1/dayjs.min.js
2. put it in **the snippets folder**
3. use it in `function.js`

```js
export function datetime() {
  return dayjs().format('YYYY-MM-DD HH:mm:ss')
}

export function date() {
  return dayjs().format('YYYY-MM-DD')
}

export function time() {
  return dayjs().format('HH:mm:ss')
}
```

**Comment by thob** [comment]
cool, I will investigate it later, I remember there were users requesting this feature from Typora natively

**Comment by thob** [comment]
works like a charm, thanks – I guess this js option opens up a lot of potential helper scripts
