### ISSUE TITLE
inserting alerts needs replacing of square bracket

### ISSUE THREAD

**Issue by thob** [typora-community-plugin/typora-plugin-note-snippets#4]
If I add an alert to the snippets file like this

![2024-12-01_14-11](https://github.com/user-attachments/assets/3bee43e1-1038-4ef3-b93e-edb56fed76b0)

and insert it via /

I always need to replace the closing bracket if not I get this
![2024-12-01_14-04](https://github.com/user-attachments/assets/90e00db7-c21b-4d0d-b2ec-f320c860799b)

after deleting/adding the closing bracket i get what I want

![2024-12-01_14-04_1](https://github.com/user-attachments/assets/ec0b331d-ed19-4e7d-850f-d517719b6eed)

Am I missing something?
Thanks

**Comment by plylrnsdy** [comment]
you can try this:

![image](https://github.com/user-attachments/assets/466d96a2-95d0-4b8c-beae-4dc42808e3ca)

**Comment by thob** [comment]
that helps, I only have to <return> for the next line. Thanks.
